// <auto-generated />
using System;
using AnyaStore.Services.CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnyaStore.Services.CouponAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240129075601_Coupon_seed_data_auto_time")]
    partial class Coupon_seed_data_auto_time
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnyaStore.Services.CouponAPI.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<string>("CouponCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MinAmount")
                        .HasColumnType("int");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            CouponCode = "10OFF",
                            CreatedOn = new DateTime(2024, 1, 29, 14, 56, 1, 91, DateTimeKind.Local).AddTicks(7392),
                            DiscountAmount = 10.0,
                            LastUpdated = new DateTime(2024, 1, 29, 14, 56, 1, 91, DateTimeKind.Local).AddTicks(7377),
                            MinAmount = 100
                        },
                        new
                        {
                            CouponId = 2,
                            CouponCode = "20OFF",
                            CreatedOn = new DateTime(2024, 1, 29, 14, 56, 1, 91, DateTimeKind.Local).AddTicks(7431),
                            DiscountAmount = 20.0,
                            LastUpdated = new DateTime(2024, 1, 29, 14, 56, 1, 91, DateTimeKind.Local).AddTicks(7430),
                            MinAmount = 200
                        },
                        new
                        {
                            CouponId = 3,
                            CouponCode = "30OFF",
                            CreatedOn = new DateTime(2024, 1, 29, 14, 56, 1, 91, DateTimeKind.Local).AddTicks(7443),
                            DiscountAmount = 30.0,
                            LastUpdated = new DateTime(2024, 1, 29, 14, 56, 1, 91, DateTimeKind.Local).AddTicks(7442),
                            MinAmount = 300
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
