// <auto-generated />
using System;
using AnyaStore.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnyaStore.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnyaStore.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CreatedOn = new DateTime(2024, 2, 23, 17, 35, 26, 126, DateTimeKind.Local).AddTicks(615),
                            Description = "Ultrabook gaming",
                            ImageUrl = "https://placehold.co/603x403",
                            LastUpdated = new DateTime(2024, 2, 23, 17, 35, 26, 126, DateTimeKind.Local).AddTicks(596),
                            Name = "Zephyrus g16",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 2,
                            CreatedOn = new DateTime(2024, 2, 23, 17, 35, 26, 126, DateTimeKind.Local).AddTicks(697),
                            Description = "Ultrabook for working",
                            ImageUrl = "https://placehold.co/603x403",
                            LastUpdated = new DateTime(2024, 2, 23, 17, 35, 26, 126, DateTimeKind.Local).AddTicks(695),
                            Name = "Macbook pro 16 m3",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 3,
                            CreatedOn = new DateTime(2024, 2, 23, 17, 35, 26, 126, DateTimeKind.Local).AddTicks(744),
                            Description = "Ultrabook for business",
                            ImageUrl = "https://placehold.co/603x403",
                            LastUpdated = new DateTime(2024, 2, 23, 17, 35, 26, 126, DateTimeKind.Local).AddTicks(743),
                            Name = "Dell XPS 16",
                            Price = 15.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
